# Generated by Django 4.1.3 on 2022-12-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=58)),
                ('phone2', models.CharField(blank=True, max_length=58, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('email2', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
