# Generated by Django 4.1.3 on 2023-01-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OR', 'Order'), ('DL', 'Delivery'), ('AC', 'Account'), ('PR', 'Product'), ('OT', 'Other')], max_length=2)),
                ('questions', models.CharField(max_length=200)),
                ('answers', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Faqs',
            },
        ),
    ]
