# Generated by Django 4.1.3 on 2023-01-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='category',
            field=models.CharField(choices=[('', 'Select Category ↓'), ('OR', 'Order'), ('DL', 'Delivery'), ('AC', 'Account'), ('PR', 'Product'), ('OT', 'Other')], max_length=2),
        ),
    ]
