# Generated by Django 4.1.3 on 2023-01-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_color',
        ),
    ]
